version: "3"

#depends_on: o container iniciar
#dockerize: o servico do banco de dados estar no ar

services:
  mysql:
    container_name: fc_mysql
    build: ./mysql
    #command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql/db_data:/var/lib/mysql/
      - ./mysql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fc_net2

  nodejs:
    container_name: fc_nodejs
    build: ./nodejs
    tty: true
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s node index.js #aguardando container
    volumes:
      - ./nodejs:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3000:3000
    depends_on: #verificando se o container iniciou
      - mysql
    networks: #definindo grupo de rede
      - fc_net2

  nginx:
    container_name: fc_nginx
    build: ./nginx
    entrypoint: dockerize -wait http://nodejs:3000 -timeout 20s /docker-entrypoint.sh nginx -g 'daemon off;'
    ports:
      - 8000:80
    depends_on:
      - nodejs
    networks:
      - fc_net2

#criando rede
networks:
  fc_net2:
    driver: bridge
